os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10
env: SWIFT_VERSION=4.2
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift test